apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-old-guest-users
  labels:
    {{- include "dul-arclight.labels" . | nindent 4 }}
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: delete-old-guest-users
              image: 'app:latest'
              imagePullPolicy: IfNotPresent
              command:
                - ./bin/rails
                - 'devise_guests:delete_old_guest_users[{{ .Values.cronJobs.deleteOldGuestUsers.daysOld }}]'
              envFrom:
                - configMapRef:
                    name: app-config
                - secretRef:
                    name: app-secret
