kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: finding-aid-data
  labels:
    {{- include "dul-arclight.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
