apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  labels:
    {{- include "dul-arclight.labels" . | nindent 4 }}
stringData:
  client-id: {{ .Values.oidcClientId }}
  client-secret: {{ .Values.oidcClientSecret }}
  cookie-secret: {{ .Values.oidcCookieSecret }}
