apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  labels:
    {{- include "dul-arclight.labels" . | nindent 4 }}
data:
  oauth2_proxy.cfg: |
    allowed_groups = [ "{{ .Values.oidcAllowedGroup }}" ]
    email_domains = [ "*" ]
    insecure_oidc_allow_unverified_email = true
    oidc_issuer_url = "https://oauth.oit.duke.edu/oidc/"
    provider = "oidc"
    real_client_ip_header = "X-Forwarded-For"
    reverse_proxy = true
    scope = "{{ .Values.oidcScope }}"
    skip_auth_routes = [ "^/index_finding_aids\\.json$" ]
    skip_provider_button = true
    upstreams = [ "http://front-end:80/" ]
