kind: Secret
apiVersion: v1
metadata:
  name: app-secret
  labels:
    {{- include "dul-arclight.labels" . | nindent 4 }}
stringData:
  DATABASE_URL: >-
    postgresql://{{ .Values.global.postgresql.auth.username }}:{{ .Values.global.postgresql.auth.password }}@app-db:5432/{{ .Values.global.postgresql.auth.database }}
  GITLAB_TOKEN: >-
    {{ required "findingAidData.webhookToken" .Values.findingAidData.webhookToken }}
  SECRET_KEY_BASE: >-
    {{ required "secretKeyBase" .Values.secretKeyBase }}
  FINDING_AID_DATA_USERNAME: >-
    {{ required "findingAidData.deployToken.username" .Values.findingAidData.deployToken.username }}
  FINDING_AID_DATA_PASSWORD: >-
    {{ required "findingAidData.deployToken.password" .Values.findingAidData.deployToken.password }}
