apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    {{- include "dul-arclight.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dul-arclight.selectorLabels" . | nindent 4 }}
