kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: solr
  labels:
    {{- include "dul-arclight.labels" . | nindent 4 }}
spec:
  host: {{ .Values.applicationHostname }}
  port:
    targetPort: http
  path: /solr
  to:
    kind: Service
    name: front-end
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
