version: '3.7'

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - '4444:4444'
    volumes:
      - /dev/shm:/dev/shm
    environment:
      # https://github.com/SeleniumHQ/docker-selenium/issues/429
      - START_XVFB=false
    container_name: selenium

  app:
    volumes:
      - ../spec/fixtures:/data:ro
    environment:
      - RAILS_ENV=test
      - FINDING_AID_DATA=spec/fixtures
    ports:
      - '3002:3002'
    depends_on:
      - selenium
    container_name: testapp
    networks:
      default:
        # Needed for test-interactive.sh script to be able to run
        # feature specs with JS in selenium container
        aliases:
          - testapp
